<a href="https://colab.research.google.com/github/adithya1010/100-Days-of-Code/blob/main/Task-3/NaanMudhalvan_Task3_IrisLite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Task-3: Iris Species Classification**

Build a SVM model to classify iris species based on petal and sepal measurements

Project done with inputs from Gemini 1.5 Flash

**Link to Chat:**

1. https://www.getmerlin.in/share/chat/8NYZbN_84_x

**References:**
1. https://www.youtube.com/watch?v=_YPScrckx28
2. https://www.baeldung.com/cs/ml-svm-c-parameter
3. https://www.geeksforgeeks.org/regularization-in-machine-learning/
4.https://en.wikipedia.org/wiki/Scikit-learn

In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix



In [3]:
# Load the iris dataset
iris = datasets.load_iris()
X = iris.data[:, 2:]  # We'll only use petal length and width for simplicity
y = iris.target

In [4]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [5]:
# Create and train the SVM model
svm_model = SVC(kernel='linear', C=1) # Using a linear kernel for simplicity.  C is the regularization parameter.
svm_model.fit(X_train, y_train)

SVC(C=1, kernel='linear')

In [6]:
# Make predictions on the test set
y_pred = svm_model.predict(X_test)

In [7]:
# Evaluate the model
print(classification_report(y_test, y_pred, target_names=iris.target_names))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [8]:
#Example prediction (optional)
example_petal = np.array([[5.1, 2.4]]) #Example Petal Length and width
predicted_species = svm_model.predict(example_petal)
print(f"\nExample prediction: Petals at {example_petal} predict species {iris.target_names[predicted_species[0]]}")



Example prediction: Petals at [[5.1 2.4]] predict species virginica
